spring:
  datasource:
    url: jdbc:oracle:thin:@oralce_medium
    driver-class-name: oracle.jdbc.OracleDriver
    username: ADMIN
    password: Accesstonaver1!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
