spring:
  datasource:
    url: jdbc:oracle:thin:@//HOST:PORT/SERVICE
    driver-class-name: oracle.jdbc.OracleDriver
    username: 운영계정
    password: 운영비밀번호

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
